import base64
import html as html_lib
import math
import cv2
import numpy as np


class ReportV3ViewerMixin:
    @staticmethod
    def _is_korean(language):
        return str(language or "").strip().lower() == "korean"

    def _localize_report_html(self, html, language="English"):
        if not self._is_korean(language):
            return html

        replacements = [
            ("Dental Analysis Report -", "치과 AI 분석 리포트 -"),
            ("Dental AI Analysis Report", "치과 AI 분석 리포트"),
            ("Generated by Dental AI Assistant", "Dental AI Assistant 생성"),
            ("Notation:", "표기법:"),
            ("Universal (1-32)", "미국식 (1-32)"),
            ("Clinical Summary", "임상 요약"),
            ("Missing Teeth", "결손 치아"),
            ("Caries Detected", "우식 탐지"),
            ("Apical Lesions", "치근단 병소"),
            ("Report Commentary", "리포트 코멘트"),
            ("Attached Secondary Findings", "추가 캡처 소견"),
            ("Full Panorama", "전체 파노라마"),
            ("(Click on highlighted areas)", "(강조된 영역을 클릭하세요)"),
            ("Routine Checkup (Triage 3)", "정기 관찰 (Triage 3)"),
            ("Treatment Required (Triage 2)", "치료 필요 (Triage 2)"),
            ("Urgent Priority (Triage 1)", "우선 치료 필요 (Triage 1)"),
            ("Missing Tooth", "결손 치아"),
            ("Detailed Findings", "상세 소견"),
            ("Scale calibration needed for accurate measurement.", "정확한 측정을 위해 스케일 보정이 필요합니다."),
            ("Absence of tooth structure detected.", "치질 구조 결손이 확인됩니다."),
            ("Long-term absence may affect alveolar bone and adjacent tooth position.", "장기 결손은 치조골과 인접치 위치에 영향을 줄 수 있습니다."),
            ("Evaluation of the edentulous area is recommended.", "결손 부위 평가를 권장합니다."),
            ("Implant Space: Adequate", "임플란트 식립 공간 양호"),
            ("Available Safe Length", "가용 안전 높이"),
            ("Mesiodistal space", "근원심 공간"),
            ("Sinus Bone Graft (Sinus Lift) indicated.", "상악동 거상술 또는 골이식이 필요합니다."),
            ("Vertical Bone Graft / GBR indicated.", "수직 골이식 또는 GBR이 필요합니다."),
            ("CBCT verification recommended.", "CBCT 확인을 권장합니다."),
            ("Clinical Analysis:", "임상 분석:"),
            ("Analysis:", "분석:"),
            ("Tooth #", "치아 #"),
            ("Univ #", "미국식 #"),
            ("Clinical Note", "임상 메모"),
            ("Bone Loss (PBL)", "골소실 (PBL)"),
            ("Tooth Decay (Caries)", "치아 우식"),
            ("Extraction Risk (Severe Bone Loss)", "발치 위험 (심한 골소실)"),
            ("Gum Disease (Periodontitis)", "치주 질환"),
            ("Good News!", "양호 소견"),
            (
                "No major issues (Cavities, significant bone loss, or inflammation) were detected by the AI in this scan.",
                "이번 영상에서는 AI 기준으로 큰 이상 소견(우식, 심한 골소실, 염증)이 확인되지 않았습니다.",
            ),
            ("WARNING", "주의"),
            (
                "This report is generated by an Artificial Intelligence system and DOES NOT constitute a medical diagnosis. Errors may occur.",
                "이 리포트는 인공지능 시스템이 생성한 참고 자료이며 의학적 진단을 대체하지 않습니다. 오류가 포함될 수 있습니다.",
            ),
            (
                "The results are for informational purposes only. You must consult a licensed dentist for accurate diagnosis and treatment planning.",
                "본 결과는 참고용입니다. 정확한 진단과 치료 계획은 면허를 보유한 치과의사와 상담해야 합니다.",
            ),
            ("Name", "이름"),
            ("Date", "날짜"),
            ("Note", "메모"),
        ]
        for source, target in replacements:
            html = html.replace(source, target)
        return html

    def _generate_html(self, user_name, date_str, summary_data, findings, main_img, crop_source_img, bl_viz_img=None, missing_teeth=None, nerve_contours=None, sinus_contours=None, ai_commentary=None, llm_analysis=None, detailed_findings=None, per_tooth_analysis=None, report_note=None, attached_captures=None, language="English"):
        """Generates HTML content"""
        if missing_teeth is None: missing_teeth = []
        
        # Load warning icon
        warning_icon_b64 = ""
        if self.warning_icon_path.exists():
            with open(self.warning_icon_path, "rb") as f:
                warning_icon_b64 = base64.b64encode(f.read()).decode('utf-8')
                
        # Load info icon
        info_icon_b64 = ""
        if self.info_icon_path.exists():
            with open(self.info_icon_path, "rb") as f:
                info_icon_b64 = base64.b64encode(f.read()).decode('utf-8')

        # Load logo
        logo_b64 = ""
        if self.logo_path.exists():
            with open(self.logo_path, "rb") as f:
                logo_b64 = base64.b64encode(f.read()).decode('utf-8')
        
        # New Clean White Design (from report guidence)
        style = """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Pretendard', 'Malgun Gothic', 'Apple SD Gothic Neo', 'Segoe UI', sans-serif; 
            max-width: 1100px; 
            margin: 0 auto; 
            padding: 48px 64px; 
            color: #E2E8F0; 
            background: #090B20;
        }
        h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 8px; color: #FFFFFF; letter-spacing: -0.02em; }
        h2 { font-size: 1.75rem; font-weight: 700; margin-bottom: 24px; color: #CBD5E1; }
        h3 { font-size: 1.5rem; font-weight: 700; margin-bottom: 12px; color: #FFFFFF; }
        .header { margin-bottom: 48px; position: relative; }
        .header p { font-size: 1.1rem; color: #94A3B8; margin-bottom: 32px; font-weight: 500; }
        .user-info { display: flex; align-items: center; gap: 20px; }
        .user-avatar { 
            width: 72px; height: 72px; 
            border-radius: 20px; 
            background: linear-gradient(135deg, #22D3EE 0%, #0EA5E9 100%); 
            display: flex; align-items: center; justify-content: center;
            color: #0F172A; font-size: 1.75rem; font-weight: 800;
            box-shadow: 0 8px 16px rgba(14, 165, 233, 0.2);
        }
        .user-details span { display: block; margin-bottom: 2px; }
        .user-details .label { font-weight: 700; color: #94A3B8; font-size: 0.85rem; text-transform: uppercase; margin-right: 8px; }
        .user-details .value { font-weight: 600; color: #F1F5F9; font-size: 1.05rem; }
        .divider-thick { border-top: 4px solid #1E293B; margin: 32px 0; border-radius: 2px; }
        .divider { border-top: 1px solid rgba(255,255,255,0.1); margin: 32px 0; }
        .pano-container { margin-bottom: 40px; position: relative; }
        .pano-img { 
            width: 100%; 
            aspect-ratio: 16/9; 
            object-fit: contain; 
            border-radius: 24px; 
            background: #000;
            border: 1px solid rgba(255,255,255,0.1);
            box-shadow: 0 32px 64px rgba(0,0,0,0.4);
        }
        .legend { 
            display: flex; 
            justify-content: center; 
            gap: 40px; 
            margin: 32px 0;
            flex-wrap: wrap;
        }
        .legend-item { display: flex; align-items: center; gap: 10px; font-weight: 700; color: #94A3B8; font-size: 0.95rem; }
        .legend-bar { width: 40px; height: 6px; border-radius: 3px; }
        .legend-bar.triage-1 { background: #F87171; box-shadow: 0 2px 8px rgba(248, 113, 113, 0.3); } 
        .legend-bar.triage-2 { background: #FACC15; box-shadow: 0 2px 8px rgba(250, 204, 21, 0.3); } 
        .legend-bar.triage-3 { background: #4ADE80; box-shadow: 0 2px 8px rgba(74, 222, 128, 0.3); } 
        .legend-bar.implant { background: transparent; border-top: 4px solid #38BDF8; } 
        .legend-bar.missing { background: transparent; border-top: 4px dashed #64748B; } 
        
        /* Odontogram Styles - Premium Dark Version */
        .odontogram { 
            margin: 40px 0;
            padding: 24px 32px 32px;
            border-radius: 24px;
            background: rgba(15, 23, 42, 0.5);
            border: 1px solid rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(20px);
            box-shadow: 0 20px 40px rgba(0,0,0,0.2);
        }
        .odonto-title {
            margin: 0 0 20px;
            color: #38BDF8;
            font-size: 1.1rem;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }
        .odonto-shell {
            display: flex;
            justify-content: center;
            align-items: stretch;
            gap: 16px;
        }
        .odonto-side {
            width: 32px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #64748B;
            font-size: 1.1rem;
            font-weight: 800;
            letter-spacing: 0.2em;
        }
        .odonto-body { display: flex; flex-direction: column; gap: 40px; }
        .odonto-divider { height: 1px; width: 100%; background: rgba(255, 255, 255, 0.08); }
        .odonto-row { display: flex; justify-content: center; gap: 6px; }
        .odonto-cell { display: flex; flex-direction: column; align-items: center; gap: 8px; }
        
        .odonto-tooth { 
            width: 54px; 
            height: 120px; 
            position: relative;
            cursor: pointer;
            transition: all 0.2s ease;
            border-radius: 12px;
            border: 1px solid rgba(255, 255, 255, 0.1);
            background: rgba(255, 255, 255, 0.03);
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }
        .odonto-tooth:hover { transform: translateY(-2px); border-color: rgba(255, 255, 255, 0.3); }
        .odonto-tooth img { 
            width: 42px; 
            height: 90px; 
            object-fit: contain;
            filter: brightness(0) invert(0.9) drop-shadow(0 0 2px rgba(255,255,255,0.2));
            opacity: 0.85;
        }
        .odonto-tooth.flip img { transform: scaleX(-1); }
        
        /* Neon Triage Colors for Dark Mode */
        .odonto-tooth.triage-3 { background: rgba(74, 222, 128, 0.1); border-color: #4ADE80; box-shadow: inset 0 0 15px rgba(74, 222, 128, 0.1); }
        .odonto-tooth.triage-3 + .odonto-label, .odonto-cell .odonto-label.triage-3 { color: #4ADE80; }
        
        .odonto-tooth.triage-2 { background: rgba(250, 204, 21, 0.1); border-color: #FACC15; box-shadow: inset 0 0 15px rgba(250, 204, 21, 0.1); }
        .odonto-tooth.triage-2 + .odonto-label, .odonto-cell .odonto-label.triage-2 { color: #FACC15; }
        
        .odonto-tooth.triage-1 { background: rgba(248, 113, 113, 0.1); border-color: #F87171; box-shadow: inset 0 0 15px rgba(248, 113, 113, 0.1); }
        .odonto-tooth.triage-1 + .odonto-label, .odonto-cell .odonto-label.triage-1 { color: #F87171; }
        
        .odonto-tooth.missing { background: rgba(148, 163, 184, 0.05); border: 1px dashed rgba(148, 163, 184, 0.3); }
        .odonto-tooth.missing img { opacity: 0.2; filter: grayscale(1); }
        .odonto-tooth.missing + .odonto-label, .odonto-cell .odonto-label.missing { color: #64748B; }
        
        .odonto-tooth.implant { background: rgba(56, 189, 248, 0.1); border-color: #38BDF8; }
        .odonto-tooth.implant + .odonto-label, .odonto-cell .odonto-label.implant { color: #38BDF8; }
        
        .odonto-label { 
            font-size: 1.1rem;
            line-height: 1;
            font-weight: 800;
            color: #94A3B8;
        }
        .odonto-quadrant { display: flex; gap: 6px; }
        .odonto-separator { width: 4px; }
        
        /* Triage Color Codes - Synchronized with Viewer */
        .badge { display:inline-block; padding:4px 10px; margin-right:6px; border-radius:8px; font-size:0.85rem; font-weight:700; color:#fff; }
        .badge.triage-1 { background:#F87171; }
        .badge.triage-2 { background:#FACC15; color:#0F172A; }
        .badge.triage-3 { background:#4ADE80; color:#0F172A; }
        .tooth-card { 
            border: 1px solid rgba(255,255,255,0.08); 
            border-radius: 20px; 
            padding: 24px; 
            margin-bottom: 24px;
            display: flex; 
            gap: 24px; 
            background: rgba(15, 23, 42, 0.4);
            backdrop-filter: blur(10px);
        }
        .tooth-card.triage-1 { border-left: 5px solid #F87171; }
        .tooth-card.triage-2 { border-left: 5px solid #FACC15; }
        .tooth-card.triage-3 { border-left: 5px solid #4ADE80; }
        .crop-img { 
            width: 192px; 
            height: 256px; 
            object-fit: contain; 
            border-radius: 12px; 
            background: #000;
            border: 1px solid rgba(255,255,255,0.1);
            flex-shrink: 0;
        }
        .tooth-details { flex: 1; text-align: left; }
        .tooth-details h3 { font-size: 1.75rem; margin-bottom: 12px; color: #F1F5F9; }
        .finding-tag { 
            display: inline-flex; 
            align-items: center; 
            gap: 8px; 
            font-weight: 700; 
            font-size: 1.1rem;
            margin-bottom: 12px;
            color: #F87171;
        }
        .finding-tag svg, .finding-tag img { width: 24px; height: 24px; }
        .description { color: #94A3B8; font-size: 0.95rem; margin-bottom: 24px; line-height: 1.6; }
        .treatments h4 { font-size: 1.1rem; font-weight: 700; margin-bottom: 12px; color: #CBD5E1; }
        .treatments ol { padding-left: 20px; color: #94A3B8; }
        .treatments li { margin-bottom: 8px; }
        .badge { display:inline-block; padding:4px 10px; margin-right:6px; border-radius:8px; font-size:0.85rem; font-weight:700; color:#fff; }
        .badge.triage-1 { background:#F87171; }
        .badge.triage-2 { background:#FACC15; color:#0F172A; }
        .badge.triage-3 { background:#4ADE80; color:#0F172A; }
        
        .footer { 
            display: flex; 
            align-items: flex-start; 
            gap: 20px; 
            margin-top: 64px; 
            padding-top: 32px;
            border-top: 1px solid rgba(255,255,255,0.08);
            color: #64748B;
        }
        .footer-logo { color: #22D3EE; font-weight: 800; font-size: 1.5rem; }
        .footer-warning { font-size: 0.8rem; }
        
        /* New Summary Box - Clinical Glassmorphism */
        .summary-box { 
            background: linear-gradient(135deg, rgba(15, 23, 42, 0.7) 0%, rgba(30, 41, 59, 0.7) 100%); 
            padding: 32px; 
            border-radius: 24px; 
            margin-bottom: 40px; 
            border: 1px solid rgba(255, 255, 255, 0.1); 
            backdrop-filter: blur(20px);
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
        }
        .summary-title { margin-top:0; color:#22D3EE; font-size: 1.25rem; font-weight: 800; margin-bottom: 20px; text-transform: uppercase; letter-spacing: 0.1em; }
        .summary-grid { display: flex; gap: 48px; }
        .summary-item { display: flex; flex-direction: column; gap: 4px; }
        .summary-val { font-size: 2.5rem; font-weight: 800; color: #FFFFFF; font-variant-numeric: tabular-nums; }
        .summary-label { font-size: 0.75rem; color: #94A3B8; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
        
        /* AI Insight Box - Professional Dark */
        .ai-box {
            background: rgba(34, 211, 238, 0.05);
            border: 1px solid rgba(34, 211, 238, 0.2);
            border-radius: 20px;
            padding: 28px;
            margin-bottom: 40px;
            position: relative;
        }
        .ai-title {
            color: #22D3EE; 
            font-size: 1.1rem; 
            font-weight: 800; 
            margin-bottom: 16px; 
            display: flex; 
            align-items: center; 
            gap: 12px;
            text-transform: uppercase;
        }
        .ai-content { color: #E2E8F0; font-size: 1rem; line-height: 1.7; white-space: pre-wrap; }
        """

        user_initial = user_name[0].upper() if user_name else "U"

        pano_img_b64 = self._encode_image(main_img)
        # Draw centerlines for all teeth on pano_img
        # Draw aligned axes for adjacent teeth (green) and guide axis (pink) on pano
        try:
            pano_draw = main_img.copy()
            # draw guide axis if available (pink)
            for mt in (missing_teeth or []):
                if isinstance(mt, dict):
                    guide = mt.get('implant_guide')
                    box = mt.get('box')
                    if guide and guide.get('line_coords') and box:
                        gx1, gy1, gx2, gy2 = map(int, guide['line_coords'])
                        # [USER REQUEST] Hide pink implant guide axis lines on full pano
                        # cv2.line(pano_draw, (gx1, gy1), (gx2, gy2), (255, 0, 255), 2)
            # draw adjacent tooth axes (green) for teeth with contours
            # [USER REQUEST] Hide green axis lines on full pano
            # for t in findings:
            #     contour = t.get('contour')
            #     if not contour: continue
            #     try:
            #         pts = np.array(contour, dtype=np.float32)
            #         if pts.ndim == 3:
            #             pts = pts.reshape(-1,2)
            #         centroid = pts.mean(axis=0)
            #         pts_c = pts - centroid
            #         cov = np.cov(pts_c, rowvar=False)
            #         eigvals, eigvecs = np.linalg.eigh(cov)
            #         vec = eigvecs[:, np.argmax(eigvals)]
            #         norm = max(np.linalg.norm(vec),1e-6)
            #         ax, ay = float(vec[0]/norm), float(vec[1]/norm)
            #         spread = np.max(np.linalg.norm(pts_c, axis=1))
            #         length = max(spread*1.2, 40)
            #         p1 = (int(centroid[0] - ax*length/2), int(centroid[1] - ay*length/2))
            #         p2 = (int(centroid[0] + ax*length/2), int(centroid[1] + ay*length/2))
            #         cv2.line(pano_draw, p1, p2, (0,255,0), 2)
            #     except Exception as e:
            #         print(f"[PANO AXIS] failed tooth {t.get('tooth_label')}: {e}")
            pano_img_b64 = self._encode_image(pano_draw)
        except Exception as e:
            print(f"[PANO AXIS] draw failed: {e}")
        
        report_reference_html = ""
        if report_note:
            report_reference_html = f"""
            <div class="divider"></div>
            <div style="margin: 24px 0 32px; padding: 24px 32px; border-radius: 24px; background: rgba(34, 211, 238, 0.05); border: 1px solid rgba(34, 211, 238, 0.2);">
                <div style="font-size: 0.85rem; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; color: #22D3EE; margin-bottom: 12px;">Report Commentary</div>
                <div style="font-size: 1.05rem; line-height: 1.7; color: #E2E8F0; white-space: pre-wrap;">{html_lib.escape(str(report_note or ''))}</div>
            </div>
            """

        attached_captures_html = ""
        if attached_captures:
            capture_cards_html = "".join(
                f"""
                <div style="padding:16px; border-radius:18px; background:rgba(0,0,0,0.3); border:1px solid rgba(255,255,255,0.06);">
                    <img src="{html_lib.escape(str(capture.get('dataUrl') or ''))}" alt="{html_lib.escape(str(capture.get('label') or 'Capture'))}" style="display:block; width:100%; max-height:220px; object-fit:contain; border-radius:12px; background:#000;" />
                    <div style="margin-top:14px; font-size:0.9rem; color:#F1F5F9; font-weight:800;">{html_lib.escape(str(capture.get('createdAt') or capture.get('label') or 'Capture'))}</div>
                </div>
                """
                for capture in attached_captures
                if capture.get('dataUrl') and len(str(capture.get('dataUrl'))) > 100
            )
            if capture_cards_html:
                attached_captures_html = f"""
                <div class="divider"></div>
                <div style="margin: 24px 0 40px; padding: 32px; border-radius: 24px; background: rgba(15, 23, 42, 0.4); border: 1px solid rgba(255, 255, 255, 0.08);">
                    <div style="font-size: 0.85rem; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; color: #94A3B8; margin-bottom: 20px;">Attached Secondary Findings</div>
                    <div style="display:grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 20px;">
                        {capture_cards_html}
                    </div>
                </div>
                """

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Dental Analysis Report - {user_name}</title>
            <style>
{style}
            
            /* Toggle Button Style */
            .notation-toggle {{
                background: #fff;
                cursor: pointer;
                border: 1px solid #ddd;
                padding: 5px 10px;
                border-radius: 20px;
                font-size: 0.8rem;
                color: #666;
                display: inline-flex;
                align-items: center;
                gap: 5px;
                transition: all 0.2s;
            }}
            .notation-toggle:hover {{ background: #f9fafb; border-color: #bbb; }}
            
            /* Logic for switching display */
            body.use-universal .format-fdi {{ display: none !important; }}
            body.use-universal .format-univ {{ display: inline !important; }}
            
            body:not(.use-universal) .format-fdi {{ display: inline !important; }}
            body:not(.use-universal) .format-univ {{ display: none !important; }}
            </style>
            <script>
            window.toggleNotation = function() {{
                document.body.classList.toggle('use-universal');
                const btns = document.querySelectorAll('.notation-toggle');
                const isUniv = document.body.classList.contains('use-universal');
                btns.forEach(btn => {{
                    btn.innerHTML = isUniv ? 'Notation: <strong>Universal (1-32)</strong>' : 'Notation: <strong>FDI (11-48)</strong>';
                }});
            }};
            </script>
        </head>
        <body>
            <div class="header">
                <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                    <img src="data:image/png;base64,{logo_b64}" style="height:120px; margin-top:-15px; margin-bottom:10px; display: block; filter: brightness(0) invert(1);">
                    <button id="btn-notation" class="notation-toggle" onclick="window.toggleNotation()">Notation: <strong>FDI (11-48)</strong></button>
                </div>
                <h1 style="color: #F1F5F9;">Dental AI Analysis Report</h1>
                <p style="color: #94A3B8;">Generated by Dental AI Assistant</p>
                
                <div class="user-info">
                    <div class="user-avatar">{user_initial}</div>
                    <div class="user-details">
                        <span><span class="label">Name</span> {user_name}</span>
                        <span><span class="label">Date</span> {date_str}</span>
                    </div>
                </div>
            </div>
            
            <div class="divider-thick"></div>

    

            <!-- EXECUTIVE SUMMARY -->
            <div class="summary-box">
                <h2 class="summary-title">Clinical Summary </h2>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="summary-val">{len(missing_teeth)}</span>
                        <span class="summary-label">Missing Teeth</span>
                    </div>
                    <div class="summary-item">
                        <span class="summary-val">{len(summary_data.get('caries', []))}</span>
                        <span class="summary-label">Caries Detected</span>
                    </div>
                    <div class="summary-item">
                        <span class="summary-val">{len(summary_data.get('periapical', []))}</span>
                        <span class="summary-label">Apical Lesions</span>
                    </div>

                </div>
            </div>

            <!-- AI INSIGHT REMOVED: Now using per-tooth analysis in each card -->

            <div class="pano-container" id="pano-wrapper">
                <h2>Full Panorama <span style="font-size:0.7em;color:#666;font-weight:normal;">(Click on highlighted areas)</span></h2>
                <div style="position:relative;display:inline-block;width:100%;">
                    <img class="pano-img" id="pano-img" src="data:image/jpeg;base64,{pano_img_b64}" alt="Full Panorama">
                    <svg class="pano-overlay" id="pano-svg" viewBox="0 0 1000 500" preserveAspectRatio="none">
                        <!-- Hotspots will be added dynamically -->
                    </svg>
                </div>
            </div>
            
            <div class="legend">
                <div class="legend-item"><div class="legend-bar triage-3"></div><span style="color:#4ADE80">Routine Checkup (Triage 3)</span></div>
                <div class="legend-item"><div class="legend-bar triage-2"></div><span style="color:#FACC15">Treatment Required (Triage 2)</span></div>
                <div class="legend-item"><div class="legend-bar triage-1"></div><span style="color:#F87171">Urgent Priority (Triage 1)</span></div>
                <div class="legend-item"><div class="legend-bar implant"></div><span style="color:#38BDF8">Implant</span></div>
                <div class="legend-item"><div class="legend-bar missing"></div><span style="color:#64748B">Missing Tooth</span></div>
            </div>
            
            <!-- ODONTOGRAM_PLACEHOLDER -->
            
            {report_reference_html}
            {attached_captures_html}
             
            <div class="divider"></div>
             
            <h2>Detailed Findings</h2>
        """
        
        # Build tooth status map
        tooth_status = {}  # FDI -> 'triage-1'/'triage-2'/'triage-3'/'missing'/'implant'
        
        # Mark all detected teeth based on Triage logic
        for tooth in findings:
            lbl = str(tooth.get('tooth_label', ''))
            if not lbl: continue
            
            # Extract basic info
            has_caries = tooth.get('caries')
            has_perio = tooth.get('periodontitis')
            pbl_lvl_odo = tooth.get('bone_loss_level', 0)
            severe_bl = pbl_lvl_odo >= 3
            hopeless = tooth.get('hopeless')
            nerve_dist_mm = tooth.get("nerve_dist_mm", 0)
            
            # Implant Check
            if "implant" in str(tooth.get('type', '')).lower() or "fixture" in str(tooth.get('type', '')).lower():
                tooth_status[lbl] = 'implant'
                continue
                
            # Same Triage Logic as Tooth Cards
            if hopeless or tooth.get("nerve_overlap") or (nerve_dist_mm and nerve_dist_mm < 2.0):
                tooth_status[lbl] = "triage-1"
            elif severe_bl or has_perio or has_caries:
                tooth_status[lbl] = "triage-2"
            else:
                tooth_status[lbl] = "triage-3"
        
        # Fallback: Mark teeth with issues from summary_data (if populated and not already worse)
        for c in summary_data.get('caries', []):
            lbl = str(c.get('tooth_label', ''))
            if lbl and tooth_status.get(lbl) not in ['triage-1', 'implant']: tooth_status[lbl] = 'triage-2'
        
        for p in summary_data.get('periapical', []):
            lbl = str(p.get('tooth_label', ''))
            if lbl and tooth_status.get(lbl) not in ['triage-1', 'implant']: tooth_status[lbl] = 'triage-2'
        
        # Mark missing teeth
        for mt in (missing_teeth or []):
            if isinstance(mt, dict):
                lbl = str(mt.get('tooth_label', ''))
                if lbl:
                    tooth_status[lbl] = 'missing'
        
        # Generate odontogram HTML with Toggle
        def build_odonto_row_toggle(jaw, quadrants):
            """
            Builds a row of teeth with support for both FDI and Universal numbering hidden/shown via JS.
            quadrants: list of tuples (q_num, list_of_positions, reverse_list, flip_image)
            Example: ('1', [8,7,6,5,4,3,2,1], False, False)
            """
            html_row = '<div class="odonto-row">'
            
            for qi, (q_prefix, positions, reverse, flip) in enumerate(quadrants):
                html_row += '<div class="odonto-quadrant">'
                
                # Determine traversal order for rendering
                pos_list = list(reversed(positions)) if reverse else positions
                
                for pos in pos_list:
                    # FDI definition
                    fdi_str = f"{q_prefix}{pos}"
                    
                    # Universal Definition
                    # We rely on self.get_universal_label()
                    univ_str = self.get_universal_label(fdi_str)
                    
                    status = tooth_status.get(fdi_str, 'triage-3')
                    
                    # Image loading
                    icon_b64 = self._load_odonto_icon(jaw, pos)
                    flip_class = 'flip' if flip else ''
                    
                    if icon_b64:
                        html_row += f'''
                        <div class="odonto-cell" onclick="document.getElementById('tooth-{fdi_str}')?.scrollIntoView({{behavior:'smooth',block:'center'}})">
                            <div class="odonto-tooth {status} {flip_class}">
                                <img src="data:image/png;base64,{icon_b64}" alt="Tooth {fdi_str}">
                            </div>
                            <span class="odonto-label {status} format-fdi">{fdi_str}</span>
                            <span class="odonto-label {status} format-univ">{univ_str}</span>
                        </div>
                        '''
                html_row += '</div>'
                if qi == 0:
                    html_row += '<div class="odonto-separator"></div>'
            
            html_row += '</div>'
            return html_row

        # Upper jaw: Q1 (18-11) | Q2 (21-28)
        upper_row = build_odonto_row_toggle('up', [
            ('1', [8,7,6,5,4,3,2,1], False, False), 
            ('2', [1,2,3,4,5,6,7,8], False, True)
        ])
        
        # Lower jaw: Q4 (48-41) | Q3 (31-38)
        lower_row = build_odonto_row_toggle('down', [
            ('4', [8,7,6,5,4,3,2,1], False, False),
            ('3', [1,2,3,4,5,6,7,8], False, True)
        ])
        
        odontogram_html = f'''
        <div class="odontogram" style="position:relative;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:14px;">
                <h3 class="odonto-title">Dental Chart</h3>
            </div>
            <div class="odonto-shell">
                <div class="odonto-side">R</div>
                <div class="odonto-body">
                    {upper_row}
                    <div class="odonto-divider"></div>
                    {lower_row}
                </div>
                <div class="odonto-side">L</div>
            </div>
        </div>
        '''
        
        html = html.replace('<!-- ODONTOGRAM_PLACEHOLDER -->', odontogram_html)
        
        # Generate SVG hotspots for problematic teeth
        img_h, img_w = main_img.shape[:2]
        svg_hotspots = []
        
        # Collect all teeth that have issues (will add to detail section)
        issue_teeth = set()
        for mt in (missing_teeth or []):
            if isinstance(mt, dict) and mt.get('tooth_label'):
                issue_teeth.add(str(mt['tooth_label']))
        
        for tooth in findings:
            lbl = tooth.get('tooth_label')
            box = tooth.get('box')
            if not lbl or not box:
                continue
            
            # Check if this tooth has issues
            has_caries = any(c.get('tooth_label') == lbl for c in summary_data.get('caries', []))
            has_perio = any(p.get('tooth_label') == lbl for p in summary_data.get('periapical', []))
            pbl_val = tooth.get('pbl_mm', 0)
            
            if has_caries or has_perio or pbl_val > 3:
                issue_teeth.add(str(lbl))
                # Convert box to percentage for SVG viewBox (1000x500)
                x1, y1, x2, y2 = box
                sx = (x1 / img_w) * 1000
                sy = (y1 / img_h) * 500
                sw = ((x2 - x1) / img_w) * 1000
                sh = ((y2 - y1) / img_h) * 500
                
                svg_hotspots.append(f'''<rect class="pano-hotspot" x="{sx:.1f}" y="{sy:.1f}" width="{sw:.1f}" height="{sh:.1f}" 
                    style="fill:transparent;stroke:none;cursor:pointer;"
                    onclick="document.getElementById('tooth-{lbl}').scrollIntoView({{behavior:'smooth',block:'center'}})" 
                    data-tooth="{lbl}"><title>Tooth #{lbl} - Click to view details</title></rect>''')
        
        # Also add missing teeth to hotspots
        for mt in (missing_teeth or []):
            if isinstance(mt, dict):
                lbl = mt.get('tooth_label')
                box = mt.get('box')
                if lbl and box:
                    x1, y1, x2, y2 = box
                    sx = (x1 / img_w) * 1000
                    sy = (y1 / img_h) * 500
                    sw = ((x2 - x1) / img_w) * 1000
                    sh = ((y2 - y1) / img_h) * 500
                    
                    svg_hotspots.append(f'''<rect class="pano-hotspot missing" x="{sx:.1f}" y="{sy:.1f}" width="{sw:.1f}" height="{sh:.1f}" 
                        style="fill:transparent;stroke:none;cursor:pointer;"
                        onclick="document.getElementById('tooth-{lbl}').scrollIntoView({{behavior:'smooth',block:'center'}})"
                        data-tooth="{lbl}"><title>Missing Tooth #{lbl}</title></rect>''')
        
        # Insert hotspots into HTML
        if svg_hotspots:
            hotspots_html = '\n'.join(svg_hotspots)
            html = html.replace('<!-- Hotspots will be added dynamically -->', hotspots_html)

        # Problematic Teeth Generation
        # Logic: PBL > 3mm OR Caries OR Periapical OR Bone Loss
        
        has_issues = False
        
        # 0. Missing Teeth Section
        if missing_teeth:
            has_issues = True
            
            # Build lookup for neighboring teeth by FDI
            teeth_by_fdi = {}
            for t in findings:
                fdi = t.get('tooth_label')
                if fdi and t.get('box'):
                    teeth_by_fdi[str(fdi)] = t
            
            def get_neighbors(fdi_str, max_steps=4):
                """Find nearest PRESENT neighbors, walking outward past consecutive gaps."""
                try:
                    fdi = int(fdi_str)
                except:
                    return None, None
                q = fdi // 10
                n = fdi % 10
                left_t = None
                for step in range(1, max_steps + 1):
                    nn = n - step
                    if nn < 1:
                        # Handle midline crossing (Q3↔Q4, same row)
                        if q == 3:
                            cross = teeth_by_fdi.get('41')
                            if cross: left_t = cross
                        elif q == 4:
                            cross = teeth_by_fdi.get('31')
                            if cross: left_t = cross
                        break
                    cand = teeth_by_fdi.get(f"{q}{nn}")
                    if cand:
                        left_t = cand
                        break
                right_t = None
                for step in range(1, max_steps + 1):
                    nn = n + step
                    if nn > 8:
                        break
                    cand = teeth_by_fdi.get(f"{q}{nn}")
                    if cand:
                        right_t = cand
                        break
                return left_t, right_t

            # --- Group consecutive missing teeth in same quadrant ---
            def group_missing(mt_list):
                mt_dict = {}
                for mt in mt_list:
                    if isinstance(mt, dict):
                        try:
                            lbl = int(mt.get('tooth_label', 0))
                            if lbl: mt_dict[lbl] = mt
                        except: pass
                if not mt_dict:
                    return [{'type': 'single', 'mt': mt} for mt in mt_list if isinstance(mt, dict)]
                sorted_lbls = sorted(mt_dict.keys())
                groups, cur = [], [sorted_lbls[0]]
                for i in range(1, len(sorted_lbls)):
                    prev, curr = sorted_lbls[i-1], sorted_lbls[i]
                    if curr // 10 == prev // 10 and curr - prev == 1:
                        cur.append(curr)
                    else:
                        groups.append(cur)
                        cur = [curr]
                groups.append(cur)
                result = []
                for grp in groups:
                    if len(grp) == 1:
                        result.append({'type': 'single', 'mt': mt_dict[grp[0]], 'labels': grp})
                    else:
                        result.append({'type': 'group', 'mts': [mt_dict[l] for l in grp], 'labels': grp})
                return result

            missing_groups = group_missing(missing_teeth)

            for group_entry in missing_groups:
                is_group = group_entry['type'] == 'group'

                if is_group:
                    # ---- GROUPED: consecutive missing teeth ----
                    group_labels = group_entry['labels']
                    group_mts = group_entry['mts']
                    all_labels_str = ', '.join([f'#{l}' for l in group_labels])
                    first_lbl = group_labels[0]
                    last_lbl = group_labels[-1]
                    lbl = first_lbl  # for scroll anchor

                    left_t, _ = get_neighbors(str(first_lbl))
                    _, right_t = get_neighbors(str(last_lbl))

                    # Calculate combined mesiodistal gap using anchor contours
                    mm_per_px_val = 0.05
                    gap_dist_mm = 0.0
                    gap_line_coords_grp = None

                    if left_t and right_t:
                        lt_cnt = left_t.get('contour')
                        rt_cnt = right_t.get('contour')
                        if lt_cnt and rt_cnt:
                            try:
                                lc = np.array(lt_cnt, dtype=np.float32).reshape(-1, 2)
                                rc = np.array(rt_cnt, dtype=np.float32).reshape(-1, 2)
                                # Determine CEJ level from boxes
                                lt_box = left_t.get('box', [0,0,0,0])
                                rt_box = right_t.get('box', [0,0,0,0])
                                cej_y = ((lt_box[1] + lt_box[3]) / 2 + (rt_box[1] + rt_box[3]) / 2) / 2
                                is_lower_grp = (first_lbl // 10) in [3, 4]
                                lc_crown = lc[lc[:, 1] < cej_y] if is_lower_grp else lc[lc[:, 1] > cej_y]
                                rc_crown = rc[rc[:, 1] < cej_y] if is_lower_grp else rc[rc[:, 1] > cej_y]
                                if len(lc_crown) > 0 and len(rc_crown) > 0:
                                    lc_max_x = np.max(lc_crown[:, 0])
                                    rc_min_x = np.min(rc_crown[:, 0])
                                    if lc_max_x > rc_min_x:
                                        lc_max_x, rc_min_x = rc_min_x, lc_max_x
                                    gap_px = max(0.0, rc_min_x - lc_max_x)
                                    # Use average mm_per_px from any mt that has it
                                    for _mt in group_mts:
                                        _g = _mt.get('implant_guide')
                                        if _g and _g.get('dist_mm') and _g.get('line_coords'):
                                            _lc = _g.get('line_coords')
                                            _px = ((_lc[2]-_lc[0])**2 + (_lc[3]-_lc[1])**2) ** 0.5
                                            if _px > 0:
                                                mm_per_px_val = _g['dist_mm'] / _px
                                                break
                                    gap_dist_mm = gap_px * mm_per_px_val
                                    # Fallback: derive mm_per_px from stored mesiodistal_gap_mm if available
                                    if mm_per_px_val == 0.05:
                                        for _mt in group_mts:
                                            _stored_gap_mm = _mt.get('mesiodistal_gap_mm', 0)
                                            if _stored_gap_mm > 0 and gap_px > 0:
                                                mm_per_px_val = _stored_gap_mm / gap_px
                                                gap_dist_mm = _stored_gap_mm  # Use pre-computed value
                                                break
                                    # gap_line Y: average crown-level Y of both anchor contours
                                    gap_line_y = float((np.mean(lc_crown[:, 1]) + np.mean(rc_crown[:, 1])) / 2)
                                    gap_line_coords_grp = [float(lc_max_x), gap_line_y, float(rc_min_x), gap_line_y]
                            except Exception as _e:
                                print(f"[GROUP GAP] Error for group {group_labels}: {_e}")

                    # Crop spanning from left_anchor to right_anchor
                    crop_html_grp = ""
                    try:
                        all_boxes = []
                        if left_t and left_t.get('box'): all_boxes.append(left_t['box'])
                        if right_t and right_t.get('box'): all_boxes.append(right_t['box'])
                        for _mt in group_mts:
                            if _mt.get('box'): all_boxes.append(_mt['box'])
                        if all_boxes:
                            bx1 = max(0, int(min(b[0] for b in all_boxes)))
                            by1 = max(0, int(min(b[1] for b in all_boxes)))
                            bx2 = int(max(b[2] for b in all_boxes))
                            by2 = int(max(b[3] for b in all_boxes))
                            expanded_grp = [bx1, by1, bx2, by2]
                            neighbor_cnts_grp = []
                            if left_t and left_t.get('contour'): neighbor_cnts_grp.append(left_t['contour'])
                            if right_t and right_t.get('contour'): neighbor_cnts_grp.append(right_t['contour'])
                            crop_b64_grp = self._crop_and_overlay(
                                crop_source_img, expanded_grp, [], bl_viz_img, 0,
                                neighbor_contours=neighbor_cnts_grp,
                                gap_line_coords=gap_line_coords_grp
                            )
                            crop_html_grp = f'<img class="crop-img" src="data:image/jpeg;base64,{crop_b64_grp}" alt="Missing Teeth {all_labels_str}">'
                    except Exception as _e:
                        print(f"[GROUP CROP] Error: {_e}")

                    space_badge = ""
                    space_note = ""
                    if gap_dist_mm >= 6.0:
                        n_implants = max(1, int(gap_dist_mm / 7.5))
                        space_badge = f'<span style="display:inline-block;padding:4px 10px;border-radius:12px;background-color:#0ea5e9;color:white;font-size:0.8rem;font-weight:600;margin-bottom:6px;">Implant Space: Adequate ({gap_dist_mm:.1f}mm)</span>'
                        space_note = f'&#x2705; Total mesiodistal space <strong>{gap_dist_mm:.1f}mm</strong> — room for approximately <strong>{n_implants}</strong> implant(s).'
                    elif gap_dist_mm > 0:
                        space_note = f'&#x26A0;&#xFE0F; Total space <strong>{gap_dist_mm:.1f}mm</strong> — limited; orthodontic evaluation or narrow fixtures recommended.'

                    html += f"""
                    <div class="tooth-card missing" id="tooth-{lbl}">
                        {crop_html_grp}
                    <div class="tooth-details">
                        <h3>Missing Teeth: {all_labels_str}</h3>
                        <br/>
                        <div style="margin-bottom:10px; font-size:1rem; font-weight:700; color:#f8fafc;">Analysis:</div>
                        <p>Consecutive missing teeth ({len(group_labels)} teeth) are detected between {'Tooth #' + str(left_t.get('tooth_label','?')) if left_t else 'the edge'} and {'Tooth #' + str(right_t.get('tooth_label','?')) if right_t else 'the edge'}.</p>
                        </div>
                    </div>
                    """
                    continue  # Skip the individual-tooth rendering below

                # ---- SINGLE missing tooth (original flow) ----
                mt = group_entry['mt']

                # Handle both dict (new) and string (legacy/fallback)
                if isinstance(mt, dict):
                    lbl = mt.get('tooth_label', '?')
                    box = mt.get('box')
                    guide = mt.get('implant_guide')
                else:
                    lbl = str(mt)
                    box = None
                    guide = None
                
                # Molar-only distance inference (16-18, 26-28, 36-38, 46-48)
                def _is_molar(fdi_str):
                    try:
                        f = int(fdi_str)
                        return f in (16,17,18,26,27,28,36,37,38,46,47,48)
                    except:
                        return False
                is_molar = _is_molar(lbl)

                crop_html = ""
                implant_badge = ""
                implant_note = ""
                implant_guide = None  # [FIX] Initialize to avoid UnboundLocalError

                def _axis_from_contour(contour):
                    """Return principal axis unit vector (vx, vy) from contour points."""
                    try:
                        pts = np.array(contour, dtype=np.float32)
                        if pts.ndim == 3:
                            pts = pts.reshape(-1, 2)
                        pts = pts - pts.mean(axis=0)
                        cov = np.cov(pts, rowvar=False)
                        eigvals, eigvecs = np.linalg.eigh(cov)
                        # principal axis = eigenvector with largest eigenvalue
                        vec = eigvecs[:, np.argmax(eigvals)]
                        # ensure not zero
                        norm = max(np.linalg.norm(vec), 1e-6)
                        return float(vec[0]/norm), float(vec[1]/norm)
                    except Exception as e:
                        print(f"[GUIDE AXIS] PCA failed for contour: {e}")
                        return None

                def _axis_from_adjacent_floor(l_box, r_box):
                    """Tangent from adjacent tooth bottoms (lower-edge midpoints)."""
                    try:
                        lx1, ly1, lx2, ly2 = map(int, l_box)
                        rx1, ry1, rx2, ry2 = map(int, r_box)
                        lp = ((lx1+lx2)/2.0, max(ly1, ly2))
                        rp = ((rx1+rx2)/2.0, max(ry1, ry2))
                        vx = rp[0]-lp[0]
                        vy = rp[1]-lp[1]
                        return vx, vy
                    except Exception as e:
                        print(f"[GUIDE AXIS] adjacent floor tangent failed: {e}")
                        return None

                def _axis_pca(contour):
                    """Return principal axis unit vector (vx, vy) from contour points."""
                    try:
                        pts = np.array(contour, dtype=np.float32)
                        if pts.ndim == 3:
                            pts = pts.reshape(-1, 2)
                        pts = pts - pts.mean(axis=0)
                        cov = np.cov(pts, rowvar=False)
                        eigvals, eigvecs = np.linalg.eigh(cov)
                        vec = eigvecs[:, np.argmax(eigvals)]
                        norm = max(np.linalg.norm(vec), 1e-6)
                        return float(vec[0]/norm), float(vec[1]/norm)
                    except Exception as e:
                        print(f"[GUIDE AXIS] PCA failed: {e}")
                        return None
                # Generate Crop if box exists
                if box:
                    try:
                        # Find neighboring teeth for expanded crop
                        left_t, right_t = get_neighbors(lbl)
                        
                        # Get original box center
                        bx1, by1, bx2, by2 = map(int, box)
                        center_x = (bx1 + bx2) // 2
                        center_y = (by1 + by2) // 2
                        
                        # Use neighbor's dimensions as reference for proper sizing
                        if left_t and left_t.get('box'):
                            ref_box = left_t['box']
                            ref_w = int(ref_box[2] - ref_box[0])
                            ref_h = int(ref_box[3] - ref_box[1])
                        elif right_t and right_t.get('box'):
                            ref_box = right_t['box']
                            ref_w = int(ref_box[2] - ref_box[0])
                            ref_h = int(ref_box[3] - ref_box[1])
                        else:
                            # Fallback: use original box but cap dimensions
                            ref_w = min(bx2 - bx1, 200)
                            ref_h = min(by2 - by1, 300)
                        
                        # Create focused crop: 2.5 teeth wide (left tooth + gap + right extension)
                        crop_width = int(ref_w * 2.5)
                        crop_height = int(ref_h * 1.3)  # A bit taller for context
                        
                        # Calculate new box centered on missing tooth
                        new_bx1 = center_x - crop_width // 2
                        new_by1 = center_y - crop_height // 2
                        new_bx2 = center_x + crop_width // 2
                        new_by2 = center_y + crop_height // 2
                        
                        # If we have a left neighbor, shift to include it
                        if left_t and left_t.get('box'):
                            l_box = left_t['box']
                            new_bx1 = min(new_bx1, int(l_box[0]))
                            new_by1 = min(new_by1, int(l_box[1]))
                            new_by2 = max(new_by2, int(l_box[3]))
                        
                        # If we have a right neighbor, extend to include it
                        if right_t and right_t.get('box'):
                            r_box = right_t['box']
                            new_bx2 = max(new_bx2, int(r_box[2]))
                            new_by1 = min(new_by1, int(r_box[1]))
                            new_by2 = max(new_by2, int(r_box[3]))
                        
                        expanded_box = [new_bx1, new_by1, new_bx2, new_by2]
                        print(f"[CROP DEBUG] Tooth {lbl}: center=({center_x},{center_y}), ref_size=({ref_w}x{ref_h})")
                        print(f"[CROP DEBUG] expanded_box={expanded_box}")
                        
                        implant_guide = mt.get('implant_guide')
                        debug_msg = mt.get('guide_status')

                        center_axis = None
                        # Interpolate implant guide axis if missing (Axis-Interpolated, jaw-aware)
                        if implant_guide and isinstance(implant_guide, dict) and not implant_guide.get('line_coords') and is_molar:
                            try:
                                # Strategy: if both contours present, use shortest segment between them
                                left_contour = left_t.get('contour') if left_t else None
                                right_contour = right_t.get('contour') if right_t else None
                                if left_contour is not None and right_contour is not None:
                                    lc = np.array(left_contour, dtype=np.float32).reshape(-1,2)
                                    rc = np.array(right_contour, dtype=np.float32).reshape(-1,2)
                                    # compute pairwise distances
                                    dists = np.linalg.norm(lc[:,None,:] - rc[None,:,:], axis=2)
                                    idx = np.unravel_index(np.argmin(dists), dists.shape)
                                    p_left = lc[idx[0]]
                                    p_right = rc[idx[1]]
                                    vec = p_right - p_left
                                    norm = max(np.linalg.norm(vec), 1e-6)
                                    ax, ay = vec / norm
                                    center_axis = (float(ax), float(ay))
                                    # line from left point to right point
                                    implant_guide['line_coords'] = [float(p_left[0]), float(p_left[1]), float(p_right[0]), float(p_right[1])]
                                    try:
                                        quad = int(str(lbl)[0])
                                    except:
                                        quad = 0
                                    implant_guide['mode'] = implant_guide.get('mode') or ('upper' if quad in (1,2) else 'lower')
                                    implant_guide.setdefault('dist_mm', 0.0)
                                else:
                                    # 2) one contour -> that axis
                                    left_axis = _axis_pca(left_contour) if left_contour is not None else None
                                    right_axis = _axis_pca(right_contour) if right_contour is not None else None
                                    if left_axis or right_axis:
                                        ax, ay = (left_axis or right_axis)
                                        center_axis = (ax, ay)
                                        try:
                                            quad = int(str(lbl)[0])
                                        except:
                                            quad = 0
                                        if quad in (1, 2):
                                            ay = abs(ay)
                                        elif quad in (3, 4):
                                            ay = -abs(ay)
                                        center_axis = (ax, ay)
                                        axis_len = max(ref_h * 1.2, 80)
                                        gx1, gy1 = center_x, center_y
                                        gx2 = int(center_x + ax * axis_len)
                                        gy2 = int(center_y + ay * axis_len)
                                        implant_guide['line_coords'] = [gx1, gy1, gx2, gy2]
                                        implant_guide['mode'] = implant_guide.get('mode') or ('upper' if quad in (1,2) else 'lower')
                                        implant_guide.setdefault('dist_mm', 0.0)
                            except Exception as e:
                                print(f"[GUIDE AXIS] Interpolation failed for missing tooth {lbl}: {e}")

                        # Final fallback for molars: vertical axis through gap center
                        if is_molar and (not implant_guide or not implant_guide.get('line_coords')):
                            try:
                                gx1 = center_x
                                gy1 = center_y
                                # direction by jaw
                                quad = int(str(lbl)[0]) if str(lbl)[:1].isdigit() else 0
                                axis_len = max(ref_h * 1.2 if 'ref_h' in locals() else (by2 - by1), 100)
                                if quad in (1,2):  # upper
                                    ax, ay = center_axis if center_axis else (0,1)
                                    gx2, gy2 = int(center_x + ax*axis_len), int(center_y + abs(ay)*axis_len)
                                else:              # lower default
                                    ax, ay = center_axis if center_axis else (0,-1)
                                    gx2, gy2 = int(center_x + ax*axis_len), int(center_y - abs(ay)*axis_len)
                                center_axis = center_axis or (0, 1 if quad in (1,2) else -1)
                                if not implant_guide or not isinstance(implant_guide, dict):
                                    implant_guide = {}
                                implant_guide['line_coords'] = [gx1, gy1, gx2, gy2]
                                implant_guide['mode'] = implant_guide.get('mode') or ('upper' if quad in (1,2) else 'lower')
                            except Exception as e:
                                print(f"[GUIDE AXIS] Fallback axis failed for tooth {lbl}: {e}")

                        # Check if implant_guide is already provided by pano_inference (Prioritize this!)
                        if guide and guide.get('line_coords'):
                            print(f"[REPORT] Using pre-calculated implant guide for {lbl}: {guide['line_coords']}")
                            implant_guide = guide
                            # Ensure mode is set
                            if 'mode' not in implant_guide:
                                implant_guide['mode'] = 'upper' if str(lbl).startswith(('1','2')) else 'lower'
                        else:
                            # Fallback: Isosceles-based centerline using adjacent centers and nearest nerve point (all missing teeth)
                            try:
                                if left_t and right_t and left_t.get('box') and right_t.get('box'):
                                    lx1, ly1, lx2, ly2 = map(int, left_t['box'])
                                    rx1, ry1, rx2, ry2 = map(int, right_t['box'])
                                    lc = ((lx1+lx2)/2.0, (ly1+ly2)/2.0)
                                    rc = ((rx1+rx2)/2.0, (ry1+ry2)/2.0)
                                    base_mid = ((lc[0]+rc[0])/2.0, (lc[1]+rc[1])/2.0)
                                    nerve_pt = None
                                    if nerve_contours:
                                        pts = np.concatenate([np.array(c) for c in nerve_contours], axis=0)
                                        dists = ((pts[:,0]-base_mid[0])**2 + (pts[:,1]-base_mid[1])**2)
                                        idx = int(np.argmin(dists))
                                        nerve_pt = (float(pts[idx,0]), float(pts[idx,1]))
                                    if nerve_pt:
                                        ax = nerve_pt[0] - base_mid[0]
                                        ay = nerve_pt[1] - base_mid[1]
                                        norm = max((ax*ax + ay*ay) ** 0.5, 1e-6)
                                        center_axis = (ax/norm, ay/norm)
                                        if not implant_guide or not isinstance(implant_guide, dict):
                                            implant_guide = {}
                                        implant_guide['line_coords'] = [base_mid[0], base_mid[1], nerve_pt[0], nerve_pt[1]]
                                        implant_guide['mode'] = implant_guide.get('mode') or ('upper' if str(lbl).startswith(('1','2')) else 'lower')
                                        implant_guide.setdefault('dist_mm', 0.0)
                            except Exception as e:
                                print(f"[GUIDE AXIS] isosceles centerline failed for tooth {lbl}: {e}")

                        # Get tooth contours for adjacent teeth if nerve overlap
                        neighbor_contours = []
                        if left_t and left_t.get('contour'):
                            neighbor_contours.append(left_t['contour'])
                        if right_t and right_t.get('contour'):
                            neighbor_contours.append(right_t['contour'])
                        
                        # Use pre-computed gap line points from tooth_logic (interproximal method)
                        gap_line_coords_for_crop = None
                        _gap_pts = mt.get('gap_line_pts') if isinstance(mt, dict) else None
                        _gap_mm = mt.get('mesiodistal_gap_mm', 0) if isinstance(mt, dict) else 0
                        if _gap_pts and len(_gap_pts) == 4 and _gap_mm >= 6.0:
                            gap_line_coords_for_crop = _gap_pts

                        crop_b64 = self._crop_and_overlay(
                            crop_source_img, 
                            expanded_box, 
                            [], 
                            bl_viz_img, 
                            0, 
                            implant_guide=implant_guide if is_molar else None,
                            # Upper jaw (1x, 2x): no nerve. Lower jaw (3x, 4x): show nerve
                            nerve_contours=nerve_contours if is_molar and str(lbl).startswith(('3', '4')) else None,
                            sinus_contours=None,  # Already disabled
                            debug_text=debug_msg,
                            nerve_dist_line=mt.get('nerve_dist_line') if is_molar else None,
                            nerve_dist_mm=mt.get('nerve_dist_mm', guide.get('dist_mm', 0) if guide else 0) if is_molar else 0,
                            centerline=False,
                            centerline_axis=None,
                            tooth_label=lbl,
                            neighbor_contours=neighbor_contours,
                            gap_line_coords=gap_line_coords_for_crop
                        )

                        
                        crop_html = f"""
                            <img class="crop-img" src="data:image/jpeg;base64,{crop_b64}" alt="Missing Tooth #{lbl}">
                        """
                    except Exception as e:
                        print(f"Error cropping missing tooth {lbl}: {e}")

                # Sync updated guide back for badge logic (molars only)
                guide = implant_guide if (implant_guide and is_molar) else guide

                # Implant suitability logic
                implant_badge = ""
                implant_note = ""
                llm_obs = "Absence of tooth structure detected."
                llm_cons = "Long-term absence may affect alveolar bone and adjacent tooth position."
                llm_sugg = "Evaluation of the edentulous area is recommended."
                llm_space = ""

                # Read gap from mt directly (always populated) or from guide as fallback
                gap = mt.get('mesiodistal_gap_mm', 0) if isinstance(mt, dict) else 0

                if guide and isinstance(guide, dict):
                    dist = guide.get('dist_mm', 0)
                    mode = guide.get('mode', 'lower')
                    if not gap: gap = guide.get('mesiodistal_gap_mm', 0)
                    
                    if dist is None or dist <= 0:
                        implant_badge = ''
                        implant_note = "Scale calibration needed for accurate measurement."
                    else:
                        space_note = ""
                        space_adequate = gap >= 6.0 if gap > 0 else True

                        if gap > 0:
                            if gap < 6.0:
                                space_note = f"<br> Mesiodistal space <strong>{gap:.1f}mm</strong> — narrow."
                            else:
                                space_note = f"<br>Mesiodistal space: <strong>~{gap:.1f}mm</strong>"

                        wh_label = ""
                        if gap >= 6.0 and dist and dist > 0:
                            wh_label = f" (W: {gap:.1f}mm / H: {dist:.1f}mm)"
                        elif gap >= 6.0:
                            wh_label = f" (W: {gap:.1f}mm)"
                        elif dist and dist > 0:
                            wh_label = f" (H: {dist:.1f}mm)"
                        if dist >= 7.0 and space_adequate:
                            implant_badge = f'<span style="display:inline-block;padding:4px 10px;border-radius:12px;background-color:#0ea5e9;color:white;font-size:0.8rem;font-weight:600;margin-bottom:6px;">Implant Space: Adequate{wh_label}</span>'
                            implant_note = f"Available Safe Length <strong>{dist:.1f}mm</strong> (Total Bone ~{dist+2:.1f}mm).{space_note}"
                        elif dist >= 7.0 and not space_adequate:
                            implant_badge = ''  # No badge – narrow space
                            implant_note = f"Available Safe Length <strong>{dist:.1f}mm</strong> (Total Bone ~{dist+2:.1f}mm).{space_note}"
                        else:
                            implant_badge = ''  # No badge for bone graft cases
                            if mode == 'upper':
                                 implant_note = f"Available Safe Length <strong>{dist:.1f}mm</strong> (Total ~{dist+2:.1f}mm).<br><strong>Sinus Bone Graft (Sinus Lift)</strong> indicated.{space_note}<br>CBCT verification recommended."
                            else:
                                 implant_note = f"Available Safe Length <strong>{dist:.1f}mm</strong> (Total ~{dist+2:.1f}mm).<br><strong>Vertical Bone Graft / GBR</strong> indicated.{space_note}<br>CBCT verification recommended."

                    llm_space = implant_note

                    if llm_analysis and str(lbl) in llm_analysis:
                        la = llm_analysis[str(lbl)]
                        llm_obs = la.get('observation', llm_obs)
                        llm_cons = la.get('consideration', llm_cons)
                        llm_sugg = la.get('suggestion', llm_sugg)
                        llm_space = la.get('space_analysis', llm_space)

                # If no guide but gap is available, still show space badge
                if not implant_badge and gap > 0:
                    if gap >= 6.0:
                        implant_badge = f'<span style="display:inline-block;padding:4px 10px;border-radius:12px;background-color:#0ea5e9;color:white;font-size:0.8rem;font-weight:600;margin-bottom:6px;">Implant Space: Adequate (W: {gap:.1f}mm)</span>'
                        if not llm_space:
                            llm_space = f'Mesiodistal space: <strong>~{gap:.1f}mm</strong>'
                    elif gap < 6.0 and not llm_space:
                        llm_space = f' Mesiodistal space <strong>{gap:.1f}mm</strong> — narrow fixture may be required.'

                missing_note = html_lib.escape(str(mt.get('note') or '').strip()) if isinstance(mt, dict) else ""
                missing_note_html = (
                    f"""
                    <div style='margin-top:12px; padding:12px 14px; background:rgba(34, 211, 238, 0.05); border:1px solid rgba(34, 211, 238, 0.2); border-radius:10px;'>
                        <div style='font-size:0.74rem; font-weight:800; letter-spacing:0.1em; text-transform:uppercase; color:#22D3EE; margin-bottom:6px;'>Note</div>
                        <div style='font-size:0.95rem; color:#E2E8F0; white-space:pre-wrap;'>{missing_note}</div>
                    </div>
                    """
                    if missing_note
                    else ""
                )
                missing_analysis = llm_obs or mt.get('missing_reason', 'No tooth structure detected in the expected position; adjacent teeth present with edentulous gap.')
                if llm_space:
                    missing_analysis += f" {llm_space}"

                html += f"""
                <div class="tooth-card missing" id="tooth-{lbl}">
                        {crop_html}
                    <div class="tooth-details">
                        <h3>
                            <span class="format-fdi">Tooth #{lbl} <span style="font-size:0.8rem;color:#6b7280;font-weight:normal;">(Univ #{self.get_universal_label(str(lbl))})</span></span>
                            <span class="format-univ" style="display:none">Tooth #{self.get_universal_label(str(lbl))} <span style="font-size:0.8rem;color:#6b7280;font-weight:normal;">(FDI #{lbl})</span></span>
                        </h3>
                        <br />
                        <div style="margin-bottom:10px; font-size:1rem; font-weight:700; color:#f8fafc;">Analysis:</div>
                        <p>{missing_analysis}</p>
                        {missing_note_html}
                    </div>
                </div>
                """
        
        # Sort findings by FD1 (if available)
        try:
             # Sort by severity (if annotated) then tooth label
             def _sev_key(t):
                 return (
                     -int(t.get("severity_score", 0) or 0),
                     int(t.get('tooth_label', 99)) if str(t.get('tooth_label','0')).isdigit() else 99
                 )
             findings.sort(key=_sev_key)
        except: pass

        # Build Detailed Findings Map
        detailed_map = {}
        if detailed_findings:
            for df in detailed_findings:
                if 'tooth' in df: detailed_map[str(df['tooth'])] = df

        def _tooth_num(value):
            try:
                return int(str(value))
            except Exception:
                return None

        def _box_iou(box_a, box_b):
            try:
                ax1, ay1, ax2, ay2 = [float(v) for v in box_a]
                bx1, by1, bx2, by2 = [float(v) for v in box_b]
            except Exception:
                return 0.0
            inter_x1 = max(ax1, bx1)
            inter_y1 = max(ay1, by1)
            inter_x2 = min(ax2, bx2)
            inter_y2 = min(ay2, by2)
            inter_w = max(0.0, inter_x2 - inter_x1)
            inter_h = max(0.0, inter_y2 - inter_y1)
            inter_area = inter_w * inter_h
            if inter_area <= 0:
                return 0.0
            area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
            area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
            union = area_a + area_b - inter_area
            return inter_area / union if union > 0 else 0.0

        def _contour_box(contour):
            try:
                pts = np.array(contour, dtype=np.float32)
                if pts.ndim == 3:
                    pts = pts.reshape(-1, 2)
                if pts.ndim != 2 or pts.shape[1] != 2 or len(pts) < 3:
                    return None
                min_xy = pts.min(axis=0)
                max_xy = pts.max(axis=0)
                return [
                    float(min_xy[0]),
                    float(min_xy[1]),
                    float(max_xy[0]),
                    float(max_xy[1]),
                ]
            except Exception:
                return None

        def _box_center(box):
            try:
                x1, y1, x2, y2 = [float(v) for v in box]
            except Exception:
                return None
            return ((x1 + x2) / 2.0, (y1 + y2) / 2.0)

        def _box_diag(box):
            try:
                x1, y1, x2, y2 = [float(v) for v in box]
            except Exception:
                return 0.0
            return math.hypot(max(0.0, x2 - x1), max(0.0, y2 - y1))

        def _normalized_center_gap(box_a, box_b):
            center_a = _box_center(box_a)
            center_b = _box_center(box_b)
            if center_a is None or center_b is None:
                return float("inf")
            norm = max(_box_diag(box_a), _box_diag(box_b), 1.0)
            return math.hypot(center_a[0] - center_b[0], center_a[1] - center_b[1]) / norm

        def _finding_signature(item):
            pbl_mm = float(item.get("bone_loss_mm", 0) or 0)
            pbl_lvl = int(item.get("bone_loss_level", 0) or 0)
            bl_pct = float(item.get("bone_loss_pct", 0) or 0)
            severe_bl = pbl_lvl >= 3 or bl_pct >= 40 or pbl_mm >= 4
            hopeless = pbl_lvl >= 4 or bl_pct >= 60 or pbl_mm >= 6
            return (
                bool(item.get("caries")),
                bool(item.get("periapical")),
                severe_bl,
                hopeless,
                bool(item.get("nerve_overlap")),
            )

        def _finding_strength(item):
            pbl_mm = float(item.get("bone_loss_mm", 0) or 0)
            pbl_lvl = int(item.get("bone_loss_level", 0) or 0)
            bl_pct = float(item.get("bone_loss_pct", 0) or 0)
            max_conf = 0.0
            for finding in item.get("findings", []) or []:
                conf = float(finding.get("conf", finding.get("confidence", 0)) or 0)
                if conf > max_conf:
                    max_conf = conf
            return (
                int(item.get("nerve_overlap", 0) or 0) * 1000
                + int(pbl_lvl >= 4 or bl_pct >= 60 or pbl_mm >= 6) * 600
                + int(pbl_lvl >= 3 or bl_pct >= 40 or pbl_mm >= 4) * 300
                + pbl_lvl * 50
                + bl_pct
                + pbl_mm * 10
                + max_conf * 100
            )

        deduped_findings = []
        for item in findings:
            current_tooth = _tooth_num(item.get("tooth_label"))
            current_box = item.get("box")
            current_contour_box = _contour_box(item.get("contour"))
            current_sig = _finding_signature(item)
            replaced_index = None
            keep_current = True

            for idx, existing in enumerate(deduped_findings):
                existing_tooth = _tooth_num(existing.get("tooth_label"))
                existing_box = existing.get("box")
                existing_contour_box = _contour_box(existing.get("contour"))
                if current_tooth is None or existing_tooth is None:
                    continue
                if current_tooth // 10 != existing_tooth // 10:
                    continue
                if abs(current_tooth - existing_tooth) != 1:
                    continue
                if current_sig != _finding_signature(existing):
                    continue
                box_iou = _box_iou(current_box, existing_box)
                contour_iou = _box_iou(current_contour_box, existing_contour_box)
                center_gap = _normalized_center_gap(
                    current_contour_box or current_box,
                    existing_contour_box or existing_box,
                )
                is_duplicate_target = (
                    box_iou >= 0.58
                    or contour_iou >= 0.72
                    or (contour_iou >= 0.52 and center_gap <= 0.24)
                )
                if not is_duplicate_target:
                    continue

                if _finding_strength(item) > _finding_strength(existing):
                    replaced_index = idx
                else:
                    keep_current = False
                print(
                    "[REPORT DEDUPE] merged overlapping findings "
                    f"{existing.get('tooth_label')} and {item.get('tooth_label')} "
                    f"(box_iou={box_iou:.2f}, contour_iou={contour_iou:.2f}, center_gap={center_gap:.2f})",
                    flush=True,
                )
                break

            if replaced_index is not None:
                deduped_findings[replaced_index] = item
            elif keep_current:
                deduped_findings.append(item)

        for item in deduped_findings:
             # Check criteria
             is_problem = False
             badges = []
             desc = []
             severity_score = 0  # Higher = more critical
             
             treatments = []
             evidence = []  # [FIX] Initialize evidence list
             
             tooth_label = str(item.get("tooth_label", "Unknown"))
             tooth_note = str(item.get("note") or "").strip()
             
             # [Detail Injection] Check if we have pre-generated detailed findings (from FeedbackGenerator)
             detail_obj = detailed_map.get(tooth_label)
             
             # Synthesize Diagnosis
             diagnosis = []
             implications = []
             plan = []
             
             # Default
             title = "Check Required"
             card_class = "treatment"
             decision = "Monitor"  # Extraction / Treatment / Monitor

             pbl_mm = item.get("bone_loss_mm", 0)
             pbl_lvl = item.get("bone_loss_level", 0)
             bl_pct = item.get("bone_loss_pct", 0)
             
             has_overlap = item.get("nerve_overlap")
             
             has_caries = item.get("caries")
             has_perio = item.get("periapical")
             
             hopeless = pbl_lvl >= 4 or bl_pct >= 60 or pbl_mm >= 6
             severe_bl = pbl_lvl >= 3 or bl_pct >= 40 or pbl_mm >= 4

             # 1. Critical Factors (Structure / Foundation)
             if pbl_lvl > 0:
                  # Add PBL Badge regardless of severity (User request: 1,2 gray, 3 yellow, 4 red)
                  badges.append(f'<span class="badge pbl-{int(pbl_lvl)}">Bone Loss (PBL) Lv.{int(pbl_lvl)}</span>')
                  # is_problem = True # [FIX] Ensure tooth is shown in report even if only mild PBL (REVERTED)

             if severe_bl:
                 diagnosis.append(f"Alveolar bone loss detected (Level {pbl_lvl}, {bl_pct:.0f}% / {pbl_mm:.1f}mm).")
                 implications.append("Periodontal support compromised; mobility and tooth loss risk elevated.")
                 
                 is_problem = True
                 evidence.append(f"Bone loss level {pbl_lvl} ({bl_pct:.0f}%, {pbl_mm:.1f}mm)")

                 if hopeless:
                      plan.append("Prognosis: Hopeless. Evaluation for extraction is recommended to control infection and plan definitive prosthesis.")
                      title = "Extraction Risk (Severe Bone Loss)"
                      badges.append('<span class="badge overlap">Extraction Risk (Hopeless)</span>')
                      severity_score += 4
                 else:
                      plan.append("Prognosis: Guarded. Periodontal surgery evaluation (flap/graft) and maintenance suggested.")
                      title = "Gum Disease (Periodontitis)"
                      severity_score += 2

             # 2. Infection / Pathology
             if has_perio:
                 diagnosis.append("Periapical radiolucency observed at the root apex.")
                 implications.append("Consistent with chronic apical periodontitis or cyst formation.")
                 plan.append("Suggest clinical evaluation for endodontic therapy (RCT or Apicoectomy).")
                 if not title.startswith("Extraction") and not title.startswith("Gum Disease"): title = "Root Infection (Periapical Lesion)"
                 is_problem = True
                 badges.append('<span class="badge perio">Root Infection (Perio)</span>')
                 
                 # Look for confidence score for perio
                 perio_conf = ''
                 for f in item.get('findings', []):
                     if f.get('type') == 'periapical' and f.get('conf'):
                         perio_conf = f" ({(f.get('conf') * 100):.0f}%)"
                         break
                 evidence.append(f"Periapical lesion at apex{perio_conf}")
                 severity_score += 2

             if has_caries:
                 diagnosis.append("Radiolucency consistent with dental caries on the crown.")
                 if has_perio:
                      implications.append("Combined with apical pathology, suggesting pulpal necrosis.")
                 else:
                      implications.append("Risk of pulpal involvement if untreated.")
                 plan.append("Restorative treatment (Filling/Inlay/Crown) may be required.")
                 if not is_problem: title = "Tooth Decay (Caries)"
                 is_problem = True
                 badges.append('<span class="badge caries">Tooth Decay (Caries)</span>')
                 
                 # Look for confidence score for caries
                 caries_conf = ''
                 for f in item.get('findings', []):
                     if f.get('type') == 'caries' and f.get('conf'):
                         caries_conf = f" ({(f.get('conf') * 100):.0f}%)"
                         break
                 evidence.append(f"Caries detected{caries_conf}")
                 severity_score += 1

             # 3. Surgical Risks (Anatomy)
             if item.get("nerve_overlap"):
                  diagnosis.append(f"Root apices are superimposed on the Nerve.")
                  implications.append(f"High risk of Nerve injury during extraction/surgery.")
                  plan.append("CBCT verification is MANDATORY before any surgical intervention.")
                  title = "Anatomy Proximity (Risk)"
                  card_class = "overlap"
                  is_problem = True
                  badges.append(f'<span class="badge overlap">Nerve Proximity (Overlap)</span>')
                  evidence.append(f"Root overlaps Nerve")
                  severity_score += 2
             
             # Nerve distance (if provided)
             nerve_dist_mm = item.get("nerve_dist_mm")
             if nerve_dist_mm:
                 evidence.append(f"Nerve distance: {nerve_dist_mm:.1f}mm")
                 if nerve_dist_mm < 2.0:
                     plan.append("Severe proximity (<2mm) to nerve. Extraction/implant must be deferred until CT planning.")
                     severity_score += 2
                     card_class = "overlap"
                     badges.append('<span class="badge overlap">Critical: Nerve Distance</span>')

             # Decision matrix (deterministic)
             if hopeless or (has_perio and severe_bl) or (has_overlap and severe_bl):
                  decision = "Extraction"
             elif has_overlap:
                  decision = "Extraction"
             elif severe_bl or has_perio or has_caries:
                  decision = "Treatment"
             else:
                  decision = "Monitor"
                 
             # ==== OVERRIDE: Triage Medical Color Coding ====
             # Level 1 (Red / #dc2626): Hopeless, Nerve Overlap, Bone loss >= Lv 4
             # Level 2 (Yellow/Amber / #d97706): Periodontitis, Caries, Bone loss Lv 3
             # Level 3 (Green / #16a34a): Monitoring (Mild bone loss)
             if hopeless or item.get("nerve_overlap") or (nerve_dist_mm and nerve_dist_mm < 2.0):
                  card_class = "triage-1"
             elif severe_bl or has_perio or has_caries:
                  card_class = "triage-2"
             else:
                  card_class = "triage-3"
             
             triage_badge_html = {
                  "triage-1": '<span class="badge triage-1">Urgent Priority (Triage 1)</span>',
                  "triage-2": '<span class="badge triage-2">Treatment Required (Triage 2)</span>',
                  "triage-3": '<span class="badge triage-3">Routine Checkup (Triage 3)</span>'
             }[card_class]
             badges.insert(0, triage_badge_html)

             if tooth_note and not is_problem:
                  is_problem = True
                  title = "Clinical Note"
                  card_class = "triage-3"
                  desc.append("<strong>Analysis:</strong><br>No major AI finding was selected for this tooth, but a clinician note was added.")
             
             # Formulate Narrative
             if is_problem:
                 # Try Gemini per-tooth analysis first; skip detail_obj if Gemini succeeds
                 tooth_label_str = str(item.get('tooth_label', ''))
                 gemini_obj = per_tooth_analysis.get(tooth_label_str, {}) if per_tooth_analysis else {}
                 gemini_analysis = gemini_obj.get('analysis', '')
                 
                 if gemini_analysis:
                     # [PRIMARY] Gemini output — show ONLY Analysis + Recommendation
                     full_desc = f"<strong>Analysis:</strong><br>{gemini_analysis}"
                     desc.append(full_desc)
                 elif detail_obj:
                     # [Fallback 1] FeedbackGenerator rule-based text
                     explanation_txt = detail_obj.get('explanation', '')
                     full_desc = ""
                     if explanation_txt:
                         full_desc += f"<strong>Analysis:</strong><br>{explanation_txt}"
                     if full_desc:
                         desc.append(full_desc)
                 else:
                     # [Fallback 2] Legacy minimal heuristic
                     if not evidence:
                         evidence = diagnosis
                     full_desc = "<strong>Analysis:</strong><br>" + ". ".join(evidence[:2])
                     desc.append(full_desc)

             if is_problem:
                 has_issues = True
                 # Fix: Use 'tooth_label' instead of 'label'
                 tooth_label = item.get("tooth_label", "Unknown")
                 box = item.get("box")
                 # propagate severity for sorting
                 item["severity_score"] = severity_score
                
                 crop_b64 = ""
                 if box:
                     # Gather specific findings for this tooth for visualization
                     specific_findings = item.get("findings", [])
                     # Use pct if available, else mm (legacy)
                     pbl_val = item.get("bone_loss_pct", item.get("bone_loss_mm", 0))
                     
                     # Safety Guide (if overlap detected)
                     safety_guide = item.get("safety_guide")
                     
                     # [VISUALIZATION LOGIC]
                     # Overlap Case: Show Nerve/Sinus AND Tooth Mask
                     # Disease Case: Show ONLY Disease Box (Clean)
                    
                     show_nc = nerve_contours
                     show_sc = None
                     show_tc = None if item.get('caries') else item.get('contour') # [FIX] Hide tooth outline for Caries, otherwise show it
                     # Centerline axis from contour if available
                     center_axis = None
                     if item.get('contour'):
                         try:
                             pts = np.array(item['contour'], dtype=np.float32)
                             if pts.ndim == 3:
                                 pts = pts.reshape(-1, 2)
                             pts = pts - pts.mean(axis=0)
                             cov = np.cov(pts, rowvar=False)
                             eigvals, eigvecs = np.linalg.eigh(cov)
                             vec = eigvecs[:, np.argmax(eigvals)]
                             norm = max(np.linalg.norm(vec), 1e-6)
                             center_axis = (float(vec[0]/norm), float(vec[1]/norm))
                         except Exception:
                             center_axis = None
 
                     crop_b64 = self._crop_and_overlay(
                        crop_source_img, 
                        box, 
                        specific_findings, 
                        bl_viz_img, 
                        pbl_val,
                        # [FIX] Never show nerve for Upper Teeth (1x, 2x) to prevent crop expansion
                        nerve_contours=None if (str(tooth_label).startswith('1') or str(tooth_label).startswith('2')) else show_nc,
                        sinus_contours=show_sc,
                        safety_guide=safety_guide,
                        tooth_contour=show_tc,
                        nerve_dist_line=item.get("nerve_dist_line"),
                        nerve_dist_mm=item.get("nerve_dist_mm", 0),
                        centerline=False,
                        centerline_axis=None,
                        tooth_label=tooth_label
                     )
                 
                 # Treatment HTML
                 treatment_html = f"<div style='margin-top:10px; padding:10px; background:#f0f8ff; border-radius:5px; font-size:0.95em; color:#2980b9;'>{'<br>'.join(treatments)}</div>" if treatments else ""
                 
                 # Check for Overlay Warning to add specific caution
                 caution_msg = ""
                 show_nerve_caution = item.get("nerve_overlap")
                 if show_nerve_caution:
                     target = "Nerve"
                     caution_msg = f"""
                     <div style='margin-top:10px; padding:10px; background:#fffbeb; border-left: 4px solid #d97706; border-radius:4px; font-size:0.95em; color:#d97706;'>
                         <strong>Extraction Caution:</strong><br>
                         The tooth root overlaps with the {target}. 
                         <strong>Risk of {target} Injury.</strong><br>
                         {f'<strong>Est. Overlap Area:</strong> {item.get("overlap_area_mm2", 0):.1f} mm²<br>' if item.get("overlap_area_mm2") else ''}
                         Precise planning and CT scan are strongly recommended before extraction.
                     </div>
                     """
                 
                 # Use Clinical Title
                 finding_title = title
                 
                 tooth_note_html = (
                     f"""
                     <div style='margin-top:12px; padding:12px 14px; background:rgba(255, 255, 255, 0.03); border:1px solid rgba(255, 255, 255, 0.08); border-radius:10px;'>
                         <div style='font-size:0.75rem; font-weight:800; letter-spacing:0.1em; text-transform:uppercase; color:#94A3B8; margin-bottom:6px;'>Note</div>
                         <div style='font-size:0.95rem; color:#E2E8F0; white-space:pre-wrap;'>{html_lib.escape(tooth_note)}</div>
                     </div>
                     """
                     if tooth_note
                     else ""
                 )

                 html += f"""
                 <div class="tooth-card {card_class}" id="tooth-{tooth_label}">
                     <img class="crop-img" src="data:image/jpeg;base64,{crop_b64}">
                     <div class="tooth-details">
                         <h3>
                              <span class="format-fdi">Tooth #{tooth_label} <span style="font-size:0.8rem;color:#94A3B8;font-weight:normal;">(Univ #{self.get_universal_label(str(tooth_label))})</span></span>
                              <span class="format-univ" style="display:none">Tooth #{self.get_universal_label(str(tooth_label))} <span style="font-size:0.8rem;color:#94A3B8;font-weight:normal;">(FDI #{tooth_label})</span></span>
                          </h3>
                         <div style="margin:12px 0 8px; font-size:1.1rem; font-weight:800; color:#38BDF8;">Clinical Analysis:</div>
                         <div style="color:#E2E8F0; line-height:1.6; font-size:0.98rem;">{' '.join(desc).replace('<strong>Analysis:</strong><br>', '', 1)}</div>
                         {tooth_note_html}
                         {treatment_html}
                         {caution_msg}
                     </div>
                 </div>
                 """

        if not has_issues:
            html += """
            <div class="tooth-card">
                <div class="tooth-details">
                    <h3>Good News!</h3>
                    <p>No major issues (Cavities, significant bone loss, or inflammation) were detected by the AI in this scan.</p>
                </div>
            </div>
            """

        html += f"""
            <div class="footer">
                <div class="footer-logo"><img src="data:image/png;base64,{logo_b64}" style="height:87px;"></div>
                <div class="footer-warning" style="flex:1;">
                    <div style="display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:12px;">
                        <img src="data:image/png;base64,{warning_icon_b64}" style="height:60px; width:auto;">
                        <strong style="font-size:1.8rem; color:#dc2626;">WARNING</strong>
                    </div>
                    <div style="text-align: center;">
                        This report is generated by an Artificial Intelligence system and DOES NOT constitute a medical diagnosis. Errors may occur.<br>
                        The results are for informational purposes only. You must consult a licensed dentist for accurate diagnosis and treatment planning.
                    </div>
                </div>
            </div>
        </body>
        </html>
        """
        return self._localize_report_html(html, language)
