import { User, AlertCircle } from 'lucide-react';

export function DentalReport() {
  return (
    <div className="min-h-screen bg-white p-8 md:p-12">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-5xl font-bold mb-2">Dental AI Analysis Report</h1>
          <p className="text-2xl text-gray-600 mb-8">Generated by Dental AI Assistant</p>
          
          {/* User Info */}
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-black flex items-center justify-center">
              <User className="w-8 h-8 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="font-semibold">Name</span>
                <span className="text-gray-700">kim</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-semibold">Date</span>
                <span className="text-gray-700">2026-01-28 11:38</span>
              </div>
            </div>
          </div>
        </div>

        <div className="border-t-4 border-black mb-8"></div>

        {/* Full Panorama Section */}
        <div className="mb-8">
          <h2 className="text-3xl font-bold mb-6">Full Panorama</h2>
          
          {/* X-ray Image Placeholder */}
          <div className="w-full aspect-[16/9] bg-gray-200 mb-6 rounded-lg flex items-center justify-center">
            <span className="text-gray-400 text-lg">X-ray Image</span>
          </div>

          {/* Dental Chart */}
          <div className="mb-8">
            {/* Upper teeth */}
            <div className="flex justify-center gap-1 mb-4">
              {Array.from({ length: 16 }).map((_, i) => (
                <div key={`upper-${i}`} className="w-10 h-16 border-2 border-gray-300 rounded-t-lg"></div>
              ))}
            </div>
            
            {/* Lower teeth */}
            <div className="flex justify-center gap-1">
              {Array.from({ length: 16 }).map((_, i) => (
                <div key={`lower-${i}`} className="w-10 h-16 border-2 border-gray-300 rounded-b-lg"></div>
              ))}
            </div>
          </div>

          {/* Legend */}
          <div className="flex justify-center gap-8 mb-8">
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-black"></div>
              <span className="font-semibold">Healthy</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-red-600"></div>
              <span className="font-semibold text-red-600">Requires treatment</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-blue-600"></div>
              <span className="font-semibold text-blue-600">Implant</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-gray-300"></div>
              <span className="font-semibold text-gray-400">Missing</span>
            </div>
          </div>
        </div>

        <div className="border-t border-gray-300 mb-8"></div>

        {/* Warning Footer */}
        <div className="flex items-start gap-4 mt-12">
          <div className="text-cyan-500 font-bold text-2xl">CYBERTIED</div>
          <div className="flex-1 text-sm">
            <p className="font-bold mb-2">⚠ WARNING ⚠</p>
            <p className="text-gray-700 leading-relaxed">
              This report is generated by an Artificial Intelligence system and DOES NOT constitute a medical diagnosis. Errors may occur.<br />
              The results are for informational purposes only. You must consult a licensed dentist for accurate diagnosis and treatment planning.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
