import { ToothDetail } from './ToothDetail';

export function ToothDetailsPage() {
  return (
    <div className="min-h-screen bg-white p-8 md:p-12">
      <div className="max-w-5xl mx-auto space-y-8">
        <ToothDetail toothNumber="12" />
        <ToothDetail toothNumber="16" />

        <div className="border-t border-gray-300 mt-12 pt-8"></div>

        {/* Warning Footer */}
        <div className="flex items-start gap-4">
          <div className="text-cyan-500 font-bold text-2xl">CYBERTIED</div>
          <div className="flex-1 text-sm">
            <p className="font-bold mb-2">⚠ WARNING ⚠</p>
            <p className="text-gray-700 leading-relaxed">
              This report is generated by an Artificial Intelligence system and DOES NOT constitute a medical diagnosis. Errors may occur.<br />
              The results are for informational purposes only. You must consult a licensed dentist for accurate diagnosis and treatment planning.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
